apiVersion: v1
kind: Namespace
metadata:
  name: team-appdev
  labels:
    team: appdev
    purpose: applications
    vault-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: team-appdev
  labels:
    team: appdev
  annotations:
    vault.hashicorp.com/role: "team-appdev"
