apiVersion: v1
kind: Namespace
metadata:
  name: team-data
  labels:
    team: data
    purpose: data-engineering
    vault-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: team-data
  labels:
    team: data
  annotations:
    vault.hashicorp.com/role: "team-data"
